//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projetos.Net.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime dt_Cadastro { get; set; }
        public string Imporancia { get; set; }
        public string Status { get; set; }
        public Nullable<int> ID_Projeto { get; set; }
        public Nullable<int> ID_Responsavel { get; set; }
        public System.DateTime dt_Ini_Prev { get; set; }
        public Nullable<System.DateTime> dt_Fim_Prev { get; set; }
        public Nullable<System.DateTime> dt_Ini { get; set; }
        public Nullable<System.DateTime> dt_Fim { get; set; }
        public string Obs { get; set; }
    
        public virtual Projeto Projeto { get; set; }
        public virtual Responsavel Responsavel { get; set; }
    }
}
